import ExcelJS from 'exceljs';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Column, SummaryRow } from '@/components/reports/ReportTable';
import { StoreSettings } from '@/shared/api/settingsApi';

export interface ReportInfo {
  title: string;
  dateFrom: string;
  dateTo: string;
  filters: Record<string, any>;
  generatedBy: string;
  storeSettings: StoreSettings;
}

export interface ExportData {
  data: any[];
  columns: Column[];
  summaryRows?: SummaryRow[];
}

// Currency formatter: ₱1,234.56
export function formatCurrency(value: number): string {
  if (value === null || value === undefined || isNaN(value)) return '₱0.00';
  return new Intl.NumberFormat('en-PH', {
    style: 'currency',
    currency: 'PHP',
    minimumFractionDigits: 2,
    maximumFractionDigits: 2
  }).format(value).replace('PHP', '₱');
}

// Date formatter for report headers: August 7, 2026
export function formatDateLong(dateString: string): string {
  const date = new Date(dateString);
  return new Intl.DateTimeFormat('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  }).format(date);
}

// Date formatter for tables: YYYY-MM-DD
export function formatDateShort(dateString: string): string {
  if (!dateString) return '';
  const date = new Date(dateString);
  return date.toISOString().split('T')[0];
}

// Generate filename
export function generateFilename(title: string, dateFrom: string, dateTo: string, extension: string): string {
  const sanitizedTitle = title.replace(/\s+/g, '_');
  return `${sanitizedTitle}_${dateFrom}_to_${dateTo}.${extension}`;
}

// Generate filter summary
export function generateFilterSummary(filters: Record<string, any>): string[] {
  const summary: string[] = [];
  
  if (filters.dateFrom && filters.dateTo) {
    summary.push(`Date Range: ${formatDateLong(filters.dateFrom)} - ${formatDateLong(filters.dateTo)}`);
  }
  
  if (filters.cashierId) {
    summary.push(`Cashier ID: ${filters.cashierId}`);
  }
  
  if (filters.status && filters.status !== 'all') {
    summary.push(`Status: ${filters.status}`);
  }
  
  if (filters.categoryId) {
    summary.push(`Category ID: ${filters.categoryId}`);
  }
  
  if (filters.supplierId) {
    summary.push(`Supplier ID: ${filters.supplierId}`);
  }
  
  if (filters.productId) {
    summary.push(`Product ID: ${filters.productId}`);
  }
  
  if (filters.resolution && filters.resolution !== 'all') {
    summary.push(`Resolution: ${filters.resolution}`);
  }
  
  if (filters.approvedBy) {
    summary.push(`Approved By: ${filters.approvedBy}`);
  }
  
  if (filters.authorizationType && filters.authorizationType !== 'all') {
    summary.push(`Authorization Type: ${filters.authorizationType}`);
  }
  
  if (filters.actionType && filters.actionType !== 'all') {
    summary.push(`Action Type: ${filters.actionType}`);
  }
  
  if (filters.search) {
    summary.push(`Search: ${filters.search}`);
  }
  
  return summary;
}

// CSV Export with header and metadata
export function exportToCSV(exportData: ExportData, reportInfo: ReportInfo) {
  const { data, columns, summaryRows } = exportData;
  
  if (data.length === 0) {
    console.warn('No data to export to CSV');
    return;
  }

  const csvRows: string[] = [];
  
  // Store Information Header
  csvRows.push(`Store: ${reportInfo.storeSettings.store_name || 'ISRA HARDWARE TRADING'}`);
  csvRows.push(`Address: ${reportInfo.storeSettings.address || '—'}`);
  csvRows.push(`Contact: ${reportInfo.storeSettings.contact_number || '—'}`);
  csvRows.push(`TIN: ${reportInfo.storeSettings.tin || '—'}`);
  csvRows.push('');
  
  // Report Metadata
  csvRows.push(`Report: ${reportInfo.title}`);
  csvRows.push(`Date Generated: ${formatDateLong(new Date().toISOString())}`);
  csvRows.push(`Generated By: ${reportInfo.generatedBy}`);
  csvRows.push('');
  
  // Filters
  const filterSummary = generateFilterSummary(reportInfo.filters);
  if (filterSummary.length > 0) {
    csvRows.push('Filters:');
    filterSummary.forEach(f => csvRows.push(f));
    csvRows.push('');
  }
  
  csvRows.push(`Total Records: ${data.length}`);
  csvRows.push('');
  
  // Column Headers
  const headers = columns.map(c => c.label);
  csvRows.push(headers.join(','));
  
  // Data Rows
  const keys = columns.map(c => c.key);
  for (const row of data) {
    const values = keys.map(key => {
      const value = row[key];
      if (value === null || value === undefined) return '';
      
      // Format currency values
      if (typeof value === 'number' && 
          (columns.find(c => c.key === key)?.align === 'right' || 
           key.toLowerCase().includes('amount') || 
           key.toLowerCase().includes('price') || 
           key.toLowerCase().includes('total') ||
           key.toLowerCase().includes('sales'))) {
        return formatCurrency(value);
      }
      
      const stringValue = String(value);
      if (stringValue.includes(',') || stringValue.includes('"') || stringValue.includes('\n')) {
        return `"${stringValue.replace(/"/g, '""')}"`;
      }
      return stringValue;
    });
    csvRows.push(values.join(','));
  }
  
  // Summary Rows
  if (summaryRows && summaryRows.length > 0) {
    csvRows.push('');
    summaryRows.forEach(summary => {
      const values = columns.map(c => {
        const val = summary.values[c.key];
        if (val === undefined || val === '') return '';
        if (typeof val === 'number') return formatCurrency(val);
        return String(val);
      });
      csvRows.push([summary.label, ...values.slice(1)].join(','));
    });
  }
  
  const csvContent = csvRows.join('\n');
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement('a');
  
  if (link.download !== undefined) {
    const url = URL.createObjectURL(blob);
    link.setAttribute('href', url);
    link.setAttribute('download', generateFilename(reportInfo.title, reportInfo.dateFrom, reportInfo.dateTo, 'csv'));
    link.style.visibility = 'hidden';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }
}

// Excel Export with formatting
export async function exportToExcel(exportData: ExportData, reportInfo: ReportInfo) {
  const { data, columns, summaryRows } = exportData;
  
  if (data.length === 0) {
    console.warn('No data to export to Excel');
    return;
  }

  const workbook = new ExcelJS.Workbook();
  const worksheet = workbook.addWorksheet('Report');
  
  // Store Information
  worksheet.mergeCells('A1:D1');
  const storeCell = worksheet.getCell('A1');
  storeCell.value = reportInfo.storeSettings.store_name || 'ISRA HARDWARE TRADING';
  storeCell.font = { bold: true, size: 16 };
  storeCell.alignment = { horizontal: 'center' };
  
  worksheet.getCell('A2').value = `Address: ${reportInfo.storeSettings.address || '—'}`;
  worksheet.getCell('A3').value = `Contact: ${reportInfo.storeSettings.contact_number || '—'}`;
  worksheet.getCell('A4').value = `TIN: ${reportInfo.storeSettings.tin || '—'}`;
  
  worksheet.addRow([]);
  
  // Report Metadata
  worksheet.getCell('A6').value = `Report: ${reportInfo.title}`;
  worksheet.getCell('A7').value = `Date Generated: ${formatDateLong(new Date().toISOString())}`;
  worksheet.getCell('A8').value = `Generated By: ${reportInfo.generatedBy}`;
  
  worksheet.addRow([]);
  
  // Filters
  const filterSummary = generateFilterSummary(reportInfo.filters);
  if (filterSummary.length > 0) {
    worksheet.getCell('A10').value = 'Filters:';
    filterSummary.forEach((f, i) => {
      worksheet.getCell(`A${11 + i}`).value = f;
    });
    worksheet.addRow([]);
  }
  
  const startRow = filterSummary.length > 0 ? 11 + filterSummary.length + 2 : 12;
  
  worksheet.getCell(`A${startRow}`).value = `Total Records: ${data.length}`;
  worksheet.addRow([]);
  
  // Column Headers
  const headerRow = worksheet.addRow(columns.map(c => c.label));
  headerRow.font = { bold: true };
  headerRow.fill = {
    type: 'pattern',
    pattern: 'solid',
    fgColor: { argb: 'FFE0E0E0' }
  };
  headerRow.alignment = { horizontal: 'center' };
  
  // Data Rows
  const keys = columns.map(c => c.key);
  data.forEach(row => {
    const values = keys.map(key => {
      const value = row[key];
      if (value === null || value === undefined) return '';
      
      // Format currency values
      if (typeof value === 'number' && 
          (columns.find(c => c.key === key)?.align === 'right' || 
           key.toLowerCase().includes('amount') || 
           key.toLowerCase().includes('price') || 
           key.toLowerCase().includes('total') ||
           key.toLowerCase().includes('sales'))) {
        return value;
      }
      
      return value;
    });
    worksheet.addRow(values);
  });
  
  // Summary Rows
  if (summaryRows && summaryRows.length > 0) {
    worksheet.addRow([]);
    summaryRows.forEach(summary => {
      const values = columns.map(c => {
        const val = summary.values[c.key];
        if (val === undefined || val === '') return '';
        return val;
      });
      const row = worksheet.addRow([summary.label, ...values.slice(1)]);
      row.font = { bold: true };
      row.fill = {
        type: 'pattern',
        pattern: 'solid',
        fgColor: { argb: 'FF4472C4' }
      };
      row.font = { bold: true, color: { argb: 'FFFFFFFF' } };
    });
  }
  
  // Auto-size columns
  worksheet.columns.forEach(column => {
    let maxLength = 0;
    column.eachCell({ includeEmpty: true }, cell => {
      const value = cell.value ? String(cell.value) : '';
      maxLength = Math.max(maxLength, value.length);
    });
    column.width = Math.min(maxLength + 2, 50);
  });
  
  // Currency formatting
  keys.forEach((key, index) => {
    if (columns[index].align === 'right' || 
        key.toLowerCase().includes('amount') || 
        key.toLowerCase().includes('price') || 
        key.toLowerCase().includes('total') ||
        key.toLowerCase().includes('sales')) {
      const column = worksheet.getColumn(index + 1);
      column.numFmt = '₱#,##0.00';
    }
  });
  
  // Generate file
  const buffer = await workbook.xlsx.writeBuffer();
  const blob = new Blob([buffer], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
  const link = document.createElement('a');
  
  if (link.download !== undefined) {
    const url = URL.createObjectURL(blob);
    link.setAttribute('href', url);
    link.setAttribute('download', generateFilename(reportInfo.title, reportInfo.dateFrom, reportInfo.dateTo, 'xlsx'));
    link.style.visibility = 'hidden';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }
}

// PDF Export with formatting
export function exportToPDF(exportData: ExportData, reportInfo: ReportInfo) {
  const { data, columns, summaryRows } = exportData;
  
  if (data.length === 0) {
    console.warn('No data to export to PDF');
    return;
  }

  const doc = new jsPDF({
    orientation: columns.length > 8 ? 'landscape' : 'portrait',
    unit: 'mm',
    format: 'a4'
  });
  
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 15;
  
  let yPosition = margin;
  
  // Store Name
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text(reportInfo.storeSettings.store_name || 'ISRA HARDWARE TRADING', pageWidth / 2, yPosition, { align: 'center' });
  yPosition += 8;
  
  // Store Details
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Address: ${reportInfo.storeSettings.address || '—'}`, margin, yPosition);
  yPosition += 5;
  doc.text(`Contact: ${reportInfo.storeSettings.contact_number || '—'}`, margin, yPosition);
  yPosition += 5;
  doc.text(`TIN: ${reportInfo.storeSettings.tin || '—'}`, margin, yPosition);
  yPosition += 10;
  
  // Report Title
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text(reportInfo.title, margin, yPosition);
  yPosition += 7;
  
  // Report Metadata
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text(`Date Generated: ${formatDateLong(new Date().toISOString())}`, margin, yPosition);
  yPosition += 5;
  doc.text(`Generated By: ${reportInfo.generatedBy}`, margin, yPosition);
  yPosition += 7;
  
  // Filters
  const filterSummary = generateFilterSummary(reportInfo.filters);
  if (filterSummary.length > 0) {
    doc.setFont('helvetica', 'bold');
    doc.text('Filters:', margin, yPosition);
    yPosition += 5;
    doc.setFont('helvetica', 'normal');
    filterSummary.forEach(f => {
      doc.text(f, margin + 5, yPosition);
      yPosition += 4;
    });
    yPosition += 3;
  }
  
  doc.text(`Total Records: ${data.length}`, margin, yPosition);
  yPosition += 10;
  
  // Table Headers
  const tableHeaders = columns.map(c => c.label);
  const tableData = data.map(row => {
    return columns.map(c => {
      const value = row[c.key];
      if (value === null || value === undefined) return '';
      
      // Format currency values
      if (typeof value === 'number' && 
          (c.align === 'right' || 
           c.key.toLowerCase().includes('amount') || 
           c.key.toLowerCase().includes('price') || 
           c.key.toLowerCase().includes('total') ||
           c.key.toLowerCase().includes('sales'))) {
        return formatCurrency(value);
      }
      
      return String(value);
    });
  });
  
  // Summary for table
  const summaryData = summaryRows ? summaryRows.map(s => {
    return columns.map(c => {
      const val = s.values[c.key];
      if (val === undefined || val === '') return '';
      if (typeof val === 'number') return formatCurrency(val);
      return String(val);
    });
  }) : [];
  
  // Generate table
  autoTable(doc, {
    head: [tableHeaders],
    body: tableData,
    foot: summaryData.length > 0 ? [summaryData[summaryData.length - 1]] : undefined,
    startY: yPosition,
    margin: { top: margin, right: margin, bottom: margin, left: margin },
    styles: {
      fontSize: 8,
      cellPadding: 3,
    },
    headStyles: {
      fillColor: [68, 114, 196],
      textColor: 255,
      fontStyle: 'bold',
      halign: 'center',
    },
    footStyles: {
      fillColor: [68, 114, 196],
      textColor: 255,
      fontStyle: 'bold',
    },
    columnStyles: columns.reduce((acc, c, i) => {
      if (c.align === 'right') {
        acc[i] = { halign: 'right' };
      } else if (c.align === 'center') {
        acc[i] = { halign: 'center' };
      }
      return acc;
    }, {} as any),
    didDrawPage: (data) => {
      // Page number
      const pageNumber = doc.internal.getNumberOfPages();
      doc.setFontSize(8);
      doc.setFont('helvetica', 'normal');
      doc.text(
        `Page ${pageNumber}`,
        pageWidth / 2,
        pageHeight - 10,
        { align: 'center' }
      );
    },
  });
  
  // Save file
  doc.save(generateFilename(reportInfo.title, reportInfo.dateFrom, reportInfo.dateTo, 'pdf'));
}

// Print Export
export function printReport() {
  window.print();
}
