import { useEffect, useState } from 'react';
import { StoreSettings, getSettings } from '@/shared/api/settingsApi';
import { formatDateLong } from '@/shared/utils/reportExport';

interface ReportHeaderProps {
  title: string;
  dateFrom: string;
  dateTo: string;
  filters?: Record<string, any>;
  generatedBy?: string;
  totalRecords?: number;
}

export default function ReportHeader({
  title,
  dateFrom,
  dateTo,
  filters = {},
  generatedBy = 'Admin',
  totalRecords = 0,
}: ReportHeaderProps) {
  const [storeSettings, setStoreSettings] = useState<StoreSettings | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const loadSettings = async () => {
      try {
        const settings = await getSettings();
        setStoreSettings(settings);
      } catch (error) {
        console.error('Failed to load store settings:', error);
      } finally {
        setLoading(false);
      }
    };
    loadSettings();
  }, []);

  if (loading) {
    return (
      <div className="bg-white rounded-xl border border-gray-200 shadow-sm p-6 mb-4">
        <div className="h-6 bg-gray-200 animate-pulse rounded w-1/3 mb-2" />
        <div className="h-4 bg-gray-200 animate-pulse rounded w-1/2" />
      </div>
    );
  }

  const storeName = storeSettings?.store_name || 'ISRA HARDWARE TRADING';
  const address = storeSettings?.address || '—';
  const contact = storeSettings?.contact_number || '—';
  const tin = storeSettings?.tin || '—';

  // Generate filter summary
  const filterSummary: string[] = [];
  if (filters.dateFrom && filters.dateTo) {
    filterSummary.push(`Date Range: ${formatDateLong(filters.dateFrom)} - ${formatDateLong(filters.dateTo)}`);
  }
  if (filters.cashierId) filterSummary.push(`Cashier: ${filters.cashierId}`);
  if (filters.status && filters.status !== 'all') filterSummary.push(`Status: ${filters.status}`);
  if (filters.categoryId) filterSummary.push(`Category: ${filters.categoryId}`);
  if (filters.supplierId) filterSummary.push(`Supplier: ${filters.supplierId}`);
  if (filters.productId) filterSummary.push(`Product: ${filters.productId}`);
  if (filters.resolution && filters.resolution !== 'all') filterSummary.push(`Resolution: ${filters.resolution}`);
  if (filters.approvedBy) filterSummary.push(`Approved By: ${filters.approvedBy}`);
  if (filters.authorizationType && filters.authorizationType !== 'all') filterSummary.push(`Authorization Type: ${filters.authorizationType}`);
  if (filters.actionType && filters.actionType !== 'all') filterSummary.push(`Action Type: ${filters.actionType}`);
  if (filters.search) filterSummary.push(`Search: ${filters.search}`);

  return (
    <div className="bg-white rounded-xl border border-gray-200 shadow-sm p-6 mb-4 print:border-none print:shadow-none print:p-0 print:mb-2">
      {/* Store Information */}
      <div className="text-center mb-4 print:mb-2">
        <h1 className="text-2xl font-bold text-gray-800 print:text-lg">{storeName}</h1>
        <p className="text-sm text-gray-600">{address}</p>
        <p className="text-sm text-gray-600">Contact: {contact}</p>
        <p className="text-sm text-gray-600">TIN: {tin}</p>
      </div>

      {/* Report Information */}
      <div className="border-t border-gray-200 pt-4 print:pt-2 print:border-t-0">
        <h2 className="text-lg font-semibold text-gray-800 print:text-base">{title}</h2>
        <div className="grid grid-cols-2 gap-2 mt-2 text-sm text-gray-600 print:grid-cols-1 print:gap-1">
          <div>Date Generated: {formatDateLong(new Date().toISOString())}</div>
          <div>Generated By: {generatedBy}</div>
        </div>
      </div>

      {/* Filters */}
      {filterSummary.length > 0 && (
        <div className="border-t border-gray-200 pt-4 mt-4 print:pt-2 print:mt-2 print:border-t-0">
          <h3 className="text-sm font-semibold text-gray-700 mb-2">Applied Filters:</h3>
          <div className="text-sm text-gray-600 space-y-1">
            {filterSummary.map((filter, index) => (
              <div key={index}>{filter}</div>
            ))}
          </div>
        </div>
      )}

      {/* Total Records */}
      <div className="border-t border-gray-200 pt-4 mt-4 print:pt-2 print:mt-2 print:border-t-0">
        <div className="text-sm text-gray-600">
          <span className="font-semibold">Total Records:</span> {totalRecords}
        </div>
      </div>
    </div>
  );
}
